### ISSUE TITLE
ImportError: cannot import name '_reflect_table' from 'alembic.util.sqla_compat'

### ISSUE THREAD

**Issue by akkuman** [xzkostyan/clickhouse-sqlalchemy#380]
clickhouse-sqlalchemy don't special alembic version

when upgrade alembic from 1.14.1 -> 1.15.0 or latest

it will raise error

```
Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/app/apps/expose/management/commands/ck_migrate.py", line 10, in handle
    run_migrations(settings.CLICKHOUSE_URI)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/libs/easm_asset/cli.py", line 12, in run_migrations
    command.upgrade(alembic_cfg, "head")
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/alembic/command.py", line 483, in upgrade
    script.run_env()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/alembic/script/base.py", line 551, in run_env
    util.load_python_file(self.dir, "env.py")
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/alembic/util/pyfiles.py", line 114, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.13/site-packages/alembic/util/pyfiles.py", line 134, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/libs/easm_asset/migrations/env.py", line 29, in <module>
    from clickhouse_sqlalchemy.alembic.dialect import patch_alembic_version, include_object
  File "/usr/local/lib/python3.13/site-packages/clickhouse_sqlalchemy/alembic/dialect.py", line 13, in <module>
    from .comparators import compare_mat_view
  File "/usr/local/lib/python3.13/site-packages/clickhouse_sqlalchemy/alembic/comparators.py", line 7, in <module>
    from alembic.util.sqla_compat import _reflect_table as _alembic_reflect_table
ImportError: cannot import name '_reflect_table' from 'alembic.util.sqla_compat' (/usr/local/lib/python3.13/site-packages/alembic/util/sqla_compat.py)
```

**Comment by akkuman** [comment]
duplicate https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/368
