### PR TITLE
#374 asynch, alembic compatibility

### LINKED ISSUE #368: Broken import due to Alembic removed _reflect_table
**Describe the bug**
Alembic version 1.15 removed function `_reflect_table` from alembic/util/sqla_compat.py. This prevents the import of `clickhouse_sqlalchemy.alembic.dialect` in my alembic/env.py file as I was taking example on https://github.com/xzkostyan/clickhouse-sqlalchemy-alembic-example/blob/main/simple/migrations/env.py. 

I plan to open a PR soon. I already did a patch on a local fork of clickhouse-sqlalchemy that solve the problem.

**To Reproduce**
A minimal reproduction is to execute this python script directly with alembic 1.15
```python
from alembic.util import sqla_compat

# uncomment next line to make it work with alembic >=1.15
# sqla_compat._reflect_table = lambda inspector, table, include_cols: inspector.reflect_table(table, None)
from clickhouse_sqlalchemy.alembic.dialect import include_object, patch_alembic_version

print("OK")
```
```
Traceback (most recent call last):
  File ".../alembic/env.py", line 5, in <module>
    from clickhouse_sqlalchemy.alembic.dialect import include_object, patch_alembic_version
  File "clickhouse-sqlalchemy/clickhouse_sqlalchemy/alembic/dialect.py", line 13, in <module>
    from .comparators import compare_mat_view
  File "clickhouse-sqlalchemy/clickhouse_sqlalchemy/alembic/comparators.py", line 7, in <module>
    from alembic.util.sqla_compat import _reflect_table as _alembic_reflect_table
ImportError: cannot import name '_reflect_table' from 'alembic.util.sqla_compat'
```

**Expected behavior**
imports should works 

**Versions**

- alembic==1.15.1
- clickhouse-sqlalchemy==0.3.2
- Python 3.12.8

### LINKED ISSUE #374: Compatibility issue with asynch==0.3.0
**Describe the bug**
Cannot open a connection to ClickHouse with `asynch==0.3.0` installed:
```
self = <clickhouse_sqlalchemy.drivers.asynch.connector.AsyncAdapt_asynch_dbapi object at 0x73b49b457680>
args = ('clickhouse://test:test@127.0.0.1:9000/test',), kwargs = {}

    def connect(self, *args, **kwargs) -> 'AsyncAdapt_asynch_connection':
        return AsyncAdapt_asynch_connection(
            self,
>           await_only(self.asynch.connect(*args, **kwargs))
        )
E       AttributeError: module 'asynch' has no attribute 'connect'. Did you mean: 'connection'?

.../clickhouse_sqlalchemy/drivers/asynch/connector.py:149: AttributeError
```

**To Reproduce**
```py
from asyncio import run
from sqlalchemy.ext.asyncio import create_async_engine


async def main() -> None:
    engine = create_async_engine('clickhouse+asynch://test:test@127.0.0.1:9000/test')

    connection = await engine.connect()

run(main())
```

**Expected behavior**
Connection is successful

**Versions**
`asynch==0.3.0`
`clickhouse-sqlalchemy==0.3.2`
`Python 3.12.8`

### PR DESCRIPTION
**Pull request by mayty**
- fixes #374 
- fixes #368 

Checklist:

- [x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [x] Add or update relevant docs, in the docs folder and in code.
- [x] Ensure PR doesn't contain untouched code reformatting: spaces, etc.
- [x] Run `flake8` and fix issues.
- [x] Run `pytest` no tests failed. See https://clickhouse-sqlalchemy.readthedocs.io/en/latest/development.html.

### CODE REVIEW

**Comment by mayty** [comment]
@xzkostyan Hi, could you take a look at this PR?

File: setup.py [hunk 1]
```diff
@@ -99,7 +99,7 @@ def read_version():
         'sqlalchemy>=2.0.0,<2.1.0',
         'requests',
         'clickhouse-driver>=0.1.2',
-        'asynch>=0.2.2,<=0.2.4',
+        'asynch>=0.2.2,<0.4.0',
```
Comment (stankudrow) [inline setup.py:102]: Hello.

The version v0.2.4 and v0.2.5 are advisable to be excluded: the v0.2.4 might have (if I am not mistaken) and the v0.2.5 has issues with connection management handling logic (an [example](https://github.com/long2ice/asynch/pull/129)).

The v0.3.0 seems to be OK except some bugs that are currently under the progress (consider having a look at [this PR](https://github.com/long2ice/asynch/pull/138)) and a minor improvement [here](https://github.com/long2ice/asynch/pull/136).

Comment (stankudrow) [reply setup.py:102]: This may do:
```suggestion
        'asynch>=0.2.2,!=0.2.4,!=0.2.5,<0.4.0',
```
https://packaging.python.org/en/latest/specifications/version-specifiers/#id5
