### PR TITLE
fix: broken alembic import with alembic 1.15. Solves issue #368

### LINKED ISSUE #368: Broken import due to Alembic removed _reflect_table
**Describe the bug**
Alembic version 1.15 removed function `_reflect_table` from alembic/util/sqla_compat.py. This prevents the import of `clickhouse_sqlalchemy.alembic.dialect` in my alembic/env.py file as I was taking example on https://github.com/xzkostyan/clickhouse-sqlalchemy-alembic-example/blob/main/simple/migrations/env.py. 

I plan to open a PR soon. I already did a patch on a local fork of clickhouse-sqlalchemy that solve the problem.

**To Reproduce**
A minimal reproduction is to execute this python script directly with alembic 1.15
```python
from alembic.util import sqla_compat

# uncomment next line to make it work with alembic >=1.15
# sqla_compat._reflect_table = lambda inspector, table, include_cols: inspector.reflect_table(table, None)
from clickhouse_sqlalchemy.alembic.dialect import include_object, patch_alembic_version

print("OK")
```
```
Traceback (most recent call last):
  File ".../alembic/env.py", line 5, in <module>
    from clickhouse_sqlalchemy.alembic.dialect import include_object, patch_alembic_version
  File "clickhouse-sqlalchemy/clickhouse_sqlalchemy/alembic/dialect.py", line 13, in <module>
    from .comparators import compare_mat_view
  File "clickhouse-sqlalchemy/clickhouse_sqlalchemy/alembic/comparators.py", line 7, in <module>
    from alembic.util.sqla_compat import _reflect_table as _alembic_reflect_table
ImportError: cannot import name '_reflect_table' from 'alembic.util.sqla_compat'
```

**Expected behavior**
imports should works 

**Versions**

- alembic==1.15.1
- clickhouse-sqlalchemy==0.3.2
- Python 3.12.8

### PR DESCRIPTION
**Pull request by thomas-dufour**
- fixes #368 

Checklist:

- [x] test locally that demonstrate the correct behavior of the change. Tests should fail without the change.
- [x] Add or update relevant docs, in the docs folder and in code.
- [x] Ensure PR doesn't contain untouched code reformatting: spaces, etc.
- [x] Run `flake8` and fix issues.
- [x] Run `pytest` no tests failed. See https://clickhouse-sqlalchemy.readthedocs.io/en/latest/development.html.

### CODE REVIEW

**Comment by cemsozens** [comment]
@xzkostyan Could you take a look at this PR? It will be really helpful to merge this.

**Comment by sk-** [comment]
@xzkostyan is there any chance this PR could be reviewed and released.

The PR looks good, as the changes are the same that were done in the original alembic's [PR](https://github.com/sqlalchemy/alembic/commit/ab446ab302ffb2884d0d95e2c76650833e6ed14b#diff-26c1780bb7ccac5e553713afac0625c31b21315e7ab95a384b44013ca667e473L219-L249).

**Review by PabloReszczynski — APPROVED** [review]

**Comment by thomas-dufour** [comment]
@PabloReszczynski thx for the approval. What about merging this PR (I don't know the process in this repo)? Is there anything I need to do?

**Comment by stankudrow** [comment]
@xzkostyan , @thomas-dufour , hello.

Could you point out where are the results of the CI for this PR? I am aware about [this page](https://github.com/xzkostyan/clickhouse-sqlalchemy/actions), but are the jobs are shown here and they are just unavailable for me or they are not?

Also, this PR is necessary for the #379 , it solves the import problems in general.

@xzkostyan , who are project maintainers? Could you name them, please?

File: clickhouse_sqlalchemy/alembic/comparators.py [hunk 1]
```diff
@@ -35,10 +35,12 @@ def _extract_to_table_name(create_table_query):
...
 def _reflect_table(inspector, table):
-    if alembic_version >= (1, 11, 0):
-        return _alembic_reflect_table(inspector, table)
+    if alembic_version >= (1, 15, 0):
+        return inspector.reflect_table(table, None)
+    elif alembic_version >= (1, 11, 0):
+        return sqla_compat._reflect_table(inspector, table)
     else:
-        return _alembic_reflect_table(inspector, table, None)
+        return sqla_compat._reflect_table(inspector, table, None)
```
Comment (stankudrow) [inline clickhouse_sqlalchemy/alembic/comparators.py:43]:
```suggestion
    if alembic_version >= (1, 11, 0):
        return sqla_compat._reflect_table(inspector, table)
    return sqla_compat._reflect_table(inspector, table, None)
```
Just `if` is enough in lieu of an `elif` and then `else` clause because of immediate `return` statements.

**Review by pmirandaa — APPROVED** [review]
