### PR TITLE
Fix compatibility with asynch 0.3.1+, Alembic 1.18+, and SQLAlchemy 2.0.44+ (fixes #400)

### LINKED ISSUE #386: There is issue with commit and rollback these 2 methods in asynch scenario
https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/3dc8df9da598ac51e20e9b7bb110ae97e250fab7/clickhouse_sqlalchemy/drivers/asynch/connector.py#L178C1-L183C1
```python
def rollback(self):
      self.await_(self._connection.rollback())

def commit(self):
      self.await_(self._connection.commit())

```
Because ClickHouse does not support transaction, then will raise error:
```
xxx\asynch\connection.py", line 181, in commit
    raise NotSupportedError
asynch.errors.NotSupportedError: Code: None.
```
The report issue in asynch can check link as below:
https://github.com/long2ice/asynch/pull/91

I have check both methods in http/connector.py and native/connector.py, with pass label as below
```python
def commit(self):
        pass

    def rollback(self):
        pass
```
https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/3dc8df9da598ac51e20e9b7bb110ae97e250fab7/clickhouse_sqlalchemy/drivers/http/connector.py#L44C5-L48C13
https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/3dc8df9da598ac51e20e9b7bb110ae97e250fab7/clickhouse_sqlalchemy/drivers/native/connector.py#L42C4-L46C13

So these 2 methods in asynch/connector.py maybe also need to change as pass?

### LINKED ISSUE #393: Incompatible with Sqlalchemy v2.0.44 using asynch
On Sqlalchemy v2.0.44 I am running into the following error:

```
        if is_cursor and cursor_result.cursor is not None:
>           await cursor_result.cursor._async_soft_close()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           AttributeError: 'AsyncAdapt_asynch_cursor' object has no attribute '_async_soft_close'

```

This is caused by this commit in sqlalchemy: https://github.com/sqlalchemy/sqlalchemy/commit/2e9902a34fafff0ac6d6c521a86c7dea3d96a392

A fix could be to either add an empty method `_async_soft_close()` to `AsyncAdapt_asynch_cursor`; or to make it inherit from `AsyncAdapt_dbapi_cursor` and set `_awaitable_cursor_close: bool = False`.

### LINKED ISSUE #400: Asynch driver incompatible with asynch 0.3.1+ and SQLAlchemy 2.0.44+
**Describe the bug**

The asynch driver in clickhouse-sqlalchemy has several compatibility gaps:

1. **asynch 0.3.1+** – Parameter substitution changed from `%` formatting to Python `.format()`, which expects `{name}` instead of `%(name)s`. Queries and data containing `%` can break.
2. **SQLAlchemy 2.0.44+** – Async cursor must implement `_async_soft_close()` for proper cleanup.
3. **ClickHouse semantics** – `commit` and `rollback` are passed to the asynch engine although ClickHouse is non-transactional; these should be no-ops.

**To Reproduce**

Using the asynch driver with asynch 0.3.1+ and/or SQLAlchemy 2.0.44+ leads to parameter/format errors, deprecation warnings, or cleanup issues depending on versions. 

Example: executing a query with bound parameters fails because the driver emits `%(name)s` while asynch 0.3.1+ expects `{name}`.

**Expected behavior**

- Driver works with 0.3.1+ (correct parameter format and Connection usage).
- Compatible with SQLAlchemy 2.0.44+ async cursor lifecycle (`_async_soft_close`).
- `commit`/`rollback` are no-ops.

**Versions**

- clickhouse-sqlalchemy: current master
- asynch: 0.3.1+
- SQLAlchemy: 2.0.44+
- Python: 3.12

### PR DESCRIPTION
**Pull request by kusaku**
- fixes #386
- fixes #393
- fixes #400

Checklist:

- [x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [x] Add or update relevant docs, in the docs folder and in code.
- [x] Ensure PR doesn't contain untouched code reformatting: spaces, etc.
- [x] Run `flake8` and fix issues.
- [x] Run `pytest` no tests failed. See https://clickhouse-sqlalchemy.readthedocs.io/en/latest/development.html.

---

### Summary

- **Asynch:** support `asynch` 0.3.1+ placeholder handling, add `_async_soft_close()` for SQLAlchemy 2.0.44+, and keep async `commit`/`rollback` compatible.
- **Alembic:** support Alembic 1.18+ comparator/registry changes while keeping backward compatibility.
- **Tests:** skip the native JSON test when the driver reports `Unknown type JSON`.
- **Docs:** update supported Python/SQLAlchemy compatibility notes.
- **CI:** modernize GitHub Actions and reduce matrix size while keeping coverage and compatibility checks.

### CODE REVIEW

**Comment by frad00r4** [comment]
Hi. With asynch 4.0 executing an SQL statement with parameters in python format doesn't work correct. 

for example LIKE statements with alembic
`SELECT name FROM system.tables WHERE engine LIKE '%%View' AND database = %(database)s`

https://github.com/long2ice/asynch/tree/v0.4.0
