### ISSUE TITLE
Broken import due to Alembic removed _reflect_table

### ISSUE THREAD

**Issue by thomas-dufour** [xzkostyan/clickhouse-sqlalchemy#368]
**Describe the bug**
Alembic version 1.15 removed function `_reflect_table` from alembic/util/sqla_compat.py. This prevents the import of `clickhouse_sqlalchemy.alembic.dialect` in my alembic/env.py file as I was taking example on https://github.com/xzkostyan/clickhouse-sqlalchemy-alembic-example/blob/main/simple/migrations/env.py. 

I plan to open a PR soon. I already did a patch on a local fork of clickhouse-sqlalchemy that solve the problem.

**To Reproduce**
A minimal reproduction is to execute this python script directly with alembic 1.15
```python
from alembic.util import sqla_compat

# uncomment next line to make it work with alembic >=1.15
# sqla_compat._reflect_table = lambda inspector, table, include_cols: inspector.reflect_table(table, None)
from clickhouse_sqlalchemy.alembic.dialect import include_object, patch_alembic_version

print("OK")
```
```
Traceback (most recent call last):
  File ".../alembic/env.py", line 5, in <module>
    from clickhouse_sqlalchemy.alembic.dialect import include_object, patch_alembic_version
  File "clickhouse-sqlalchemy/clickhouse_sqlalchemy/alembic/dialect.py", line 13, in <module>
    from .comparators import compare_mat_view
  File "clickhouse-sqlalchemy/clickhouse_sqlalchemy/alembic/comparators.py", line 7, in <module>
    from alembic.util.sqla_compat import _reflect_table as _alembic_reflect_table
ImportError: cannot import name '_reflect_table' from 'alembic.util.sqla_compat'
```

**Expected behavior**
imports should works 

**Versions**

- alembic==1.15.1
- clickhouse-sqlalchemy==0.3.2
- Python 3.12.8

**Comment by sk-** [comment]
Given the lack of response we ended up adding the following code to our `env.py`, which must go before the `clickhouse_sqlalchemy.alembic.dialect` import.

```python
from alembic.util import sqla_compat
from sqlalchemy import Table
from sqlalchemy.engine.reflection import Inspector


# See https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/368
# TODO: remove once the issue is fixed
def _reflect_table(inspector: Inspector, table: Table) -> None:
    return inspector.reflect_table(table, None)


sqla_compat._reflect_table = _reflect_table  # type: ignore
```

Note: we decide to go with this solution because latest versions of alembic has much better type annotations, which in fact found some issues in our migrations.

**Comment by thomas-dufour** [comment]
Just like you, I do run my env.py with the two commented python lines uncommented. This is an equivalent hack.

**Comment by Telemaco019** [comment]
In case it helps anyone, we’ve fixed compatibility with alembic >= 1.15 in our fork: https://github.com/nebuly-ai/clickhouse-sqlalchemy
